In [1]:
import pandas as pd

In [50]:
df = pd.read_csv('test_data/devices/part-00000-cdb2cdd7-9d14-4000-b947-4d0475444217-c000.csv')

In [51]:
df

,deviceid,platform,os_version,model,networkType,district,lastknownsubadminarea,language_selected,created_datetime,app_updated_at,last_active_at
0,197b123e-eb9e-4fc1-a32d-aa86aaea425e,ANDROID,13,NaN,4G,NaN,NaN,en,2023-07-11T13:40:05.511Z,NaN,2023-07-11T13:40:02.000Z
1,3c33c537-7c6c-40f5-835c-f997e883cae2,ANDROID,13,NaN,4G,NaN,NaN,en,2023-07-11T15:36:58.363Z,NaN,2023-07-11T16:24:44.000Z
2,6c7be5d0-d4d8-469f-91be-8055021ceef9,ANDROID,12,NaN,NO INTERNET,NaN,NaN,en,2023-07-11T11:25:39.375Z,NaN,2023-07-11T10:13:18.000Z
3,0801af66-0a6f-4fdd-82a9-c2b15757b8f5,ANDROID,7.0,NaN,NO INTERNET,NaN,NaN,en,2023-04-30T00:24:48.987Z,NaN,2023-07-10T11:53:21.000Z
4,78b3c7a7-5881-42dc-9f8e-b4fc27f94360,ANDROID,13,NaN,4G,NaN,NaN,en,2023-04-15T05:48:46.923Z,NaN,2023-07-20T15:37:47.000Z
...,...,...,...,...,...,...,...,...,...,...,...
10395,2f2c7f12-919e-4692-9cf2-e1ee90238958,ANDROID,12,Xiaomi POCO M2 Pro,4G,NaN,Lawar Khas,en,2023-04-26T07:01:25.537Z,NaN,2023-07-25T09:14:37.000Z
10396,3e78edec-c369-490b-8a12-35b00b8ece36,ANDROID,12,Motorola moto g62 5G,4G,NaN,Bengaluru,en,2023-05-05T11:23:11.527Z,2023-07-22,2023-07-25T09:14:01.000Z
10397,b2c0071d-2b86-41fc-b0e3-5689e9aedef1,ANDROID,10,Xiaomi Redmi 8A Dual,WIFI,NaN,Delhi,en,2023-04-16T04:12:36.767Z,NaN,2023-07-25T03:42:12.000Z
10398,0eaa96ab-7b42-446f-a877-60aaf70dc144,ANDROID,12,Infinix Infinix X6517,4G,NaN,Limburg an der Lahn,en,2023-05-04T00:22:45.911Z,2023-06-28,2023-07-25T16:11:49.000Z
10399,017120da-5a11-4139-a438-97906a941a46,ANDROID,12,Xiaomi Redmi Note 9 Pro Max,WIFI,NaN,Vadakku Valliyur,en,2023-05-08T03:30:09.838Z,2023-06-28,2023-07-25T16:28:25.000Z

In [9]:
event_df = pd.read_csv('test_data/event/part-00000-7e210b01-29d8-430f-988f-d3e3b34da614-c000.csv')

In [59]:
event_df[event_df['deviceId'] == '7cb933f6-0a5b-477e-bb5d-42eb4b771970']

,deviceId,event_type,eventTimestamp,hashId,categoryWhenEventHappened,cardViewPosition,overallTimeSpent,searchTerm,relevancy_color,relevancy_topic,state,locality,district
0,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1689189015000,2k4lruyx-1,My Feed,13.0,2.165,NaN,NaN,NaN,NaN,NaN,NaN
479,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1689189376000,51qwydm6-1,My Feed,48.0,9.825,NaN,NaN,NaN,NaN,NaN,NaN
5444,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1689189918000,obf7bgcf-1,My Feed,91.0,9.862,NaN,NaN,NaN,NaN,NaN,NaN
6537,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1689189877000,s2mrcv53-2,My Feed,88.0,3.619,NaN,NaN,NaN,NaN,NaN,NaN
7908,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1689189190000,vubqoxud-1,My Feed,29.0,16.834,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
865406,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1690191589000,m9numd8d-1,My Feed,39.0,0.089,NaN,NaN,NaN,NaN,NaN,NaN
867375,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1690191011000,smitffko-1,My Feed,18.0,3.054,NaN,NaN,NaN,NaN,NaN,NaN
868577,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1690195090000,xr6huvuh-1,My Feed,29.0,15.212,NaN,NaN,NaN,NaN,NaN,NaN
879166,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1687891006000,4yp7hd5u-1,My Feed,2.0,28.688,NaN,NaN,NaN,NaN,NaN,NaN
884125,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1687891282000,njxwxae9-1,My Feed,17.0,25.634,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
import csv

In [60]:
path = "test_data/training_content/part-00000-a34a1545-5cf1-47b9-93c2-29c1d3f0bfb7-c000.csv"
rows = []
with open(path, newline='', encoding='utf-8') as f:
    reader = csv.reader(f)
    for row in reader:
        try:
            rows.append(row)
        except:
            print(row)
        
print("Number of rows loaded:", len(rows))
print("Max columns in a row:", max(len(r) for r in rows))

Number of rows loaded: 14636
Max columns in a row: 22

In [61]:
import pandas as pd

# Convert all rows to a DataFrame
df = pd.DataFrame(rows)

In [71]:
rows[0]

['hashid',
 'title',
 'content',
 'newsType',
 'author',
 'categories',
 'hashtags',
 'newsDistrict',
 'createdAt',
 'updatedAt',
 'newsLanguage',
 'sourceName']

In [69]:
df[14].value_counts()

14
english                     528
YouTube                     248
The Indian Express          175
Hindustan Times             162
Twitter                     111
                           ...
SpotBoye                      1
SpotboyE                      1
Dailystar                     1
2023-07-18T13:24:11.000Z      1
हिन्दुस्तान                   1
Name: count, Length: 341, dtype: int64